name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
      
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
        
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      
    - name: ServerCore.lib-Download
      uses: blauqs/actions-download-asset@v1.2
      with:
        repo: jidungg/GameServer
        version: latest
        prefix: 1.
        file: ServerCore.lib
        out: ./Libraries/ServerCore/Release/ServerCore.lib
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: ProtobufDownload
      uses: blauqs/actions-download-asset@v1.2
      with:
        repo: protocolbuffers/protobuf
        version: 21.12
        prefix: v
        file: protobuf-cpp-3.21.12.zip
        out: ../protobuf.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        unpack: false
    - name: extract-7z-action
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        # archive path to extract
        pathSource:  ../protobuf.zip
        # path to place the extract
        pathTarget:  ../protobuf
    - name: get-cmake
      # You may pin to the exact commit or the version.
      # uses: lukka/get-cmake@1a178d42f9f4f47310373da4f5ef02297ed5a6e8
      uses: lukka/get-cmake@v3.25.2
    - name: run-cmake
      # You may pin to the exact commit or the version.
      # uses: lukka/run-cmake@2d1ee0acb9c4f656ec9128fc7387d82ac4539816
      uses: lukka/run-cmake@v10.3
      with:
        # Path to CMakeLists.txt.
        cmakeListsTxtPath: ../protobuf/protobuf-3.21.12/cmake/CMakeLists.txt
        
    - name : ls
      run : |
        ls ../
        ls ../protobuf
        ls ../protobuf/protobuf-3.21.12
        ls ../protobuf/protobuf-3.21.12/cmake
        ls D:\a\_temp\1949874275\cmake-3.25.2-windows-x86_64
        ls D:\a\_temp\1949874275\cmake-3.25.2-windows-x86_64\bin\
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

