name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  PROTOBUF_VERSION: 21.12
  
permissions:
  contents: read

jobs:
      
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: ServerCore lib Download
      uses: blauqs/actions-download-asset@v1.2
      with:
        repo: jidungg/GameServer
        version: latest
        prefix: 2.
        file: ServerCore.lib
        out: ./Libraries/ServerCore/Release/ServerCore.lib
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: ServerCore header Download
      uses: blauqs/actions-download-asset@v1.2
      with:
        repo: jidungg/GameServer
        version: latest
        prefix: 2.
        file: ServerCoreHeaders.zip
        out: ./Libraries/ServerCore/ServerCoreHeaders.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        unpack: false
        
    - name : check servercore header
      run : |
        ls ./Libraries/ServerCore
        
    - name: extract ServerCore header
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource:  ./Libraries/ServerCore/ServerCoreHeaders.zip
        pathTarget:  ./Libraries/ServerCore
        
        
    - name : check servercore header
      run : |
        ls ./Libraries/ServerCore
        
    - name: Protobuf Download
      uses: blauqs/actions-download-asset@v1.2
      with:
        repo: protocolbuffers/protobuf
        version: ${{env.PROTOBUF_VERSION}}
        prefix: v
        file: protobuf-cpp-3.21.12.zip
        out: ../protobuf.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        unpack: false
        
    - name: extract protobuf
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource:  ../protobuf.zip
        pathTarget:  ../protobuf
      
    - name: Build Protobuf with CMake
      run: |
        cmake -H'../protobuf/protobuf-3.21.12/cmake' -B '../protobuf/protobuf-3.21.12/sol' 
        cmake --build  '../protobuf/protobuf-3.21.12/sol' --config ${{env.BUILD_CONFIGURATION}}
        
    - name: Move libprotobuf.lib
      run: |
        ls ../protobuf/protobuf-3.21.12/sol
        ls ../protobuf/protobuf-3.21.12/sol/${{env.BUILD_CONFIGURATION}}
        ls D:/a/Chat/Chat/Libraries/Protobuf
        mkdir D:/a/Chat/Chat/Libraries/Protobuf/${{env.BUILD_CONFIGURATION}}
        Copy-Item -Path ../protobuf/protobuf-3.21.12/sol/${{env.BUILD_CONFIGURATION}}/libprotobuf.lib -Destination D:/a/Chat/Chat/Libraries/Protobuf/${{env.BUILD_CONFIGURATION}}/libprotobuf.lib
        ls D:/a/Chat/Chat/Libraries/ServerCore/${{env.BUILD_CONFIGURATION}}
        ls D:/a/Chat/Chat/Libraries/Protobuf/${{env.BUILD_CONFIGURATION}}
        
    - name: Visual Studio shell
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/vs-shell@9a932a62d05192eae18ca370155cf877eecc2202
      uses: egor-tensin/vs-shell@v2

    - name: Build solution
      run: |
        msbuild Chat.sln /p:Configuration=${{env.BUILD_CONFIGURATION}} /m
